name: Update Submodule and Run Tests

on:
  schedule:
    - cron: '0 12 * * 4'  # Runs weekly on Thursday at midday
  workflow_dispatch:

env:
  PYTEST_ADDOPTS: "--numprocesses=logical"

permissions:
  contents: write
  pull-requests: write

jobs:
  pytest:
    strategy:
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: "true"
          cache-suffix: pytest-${{ matrix.python-version }}
          cache-dependency-glob: "pyproject.toml"
      - name: install-reqs
        run: |
            git submodule update --init --recursive
            uv pip install -e narwhals --system
            uv pip install -e . --group tests --system
            uv pip install daft --system
      - name: Configure git
        run: |
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
      - name: run-submodule-update
        run: . utils/submodule_update.sh
      - name: update-tests
        run: python update_run_tests.py
      - name: create-pull-request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: 'chore: auto-update tests and submodule'
          title: 'chore: auto-update tests and submodule'
          branch: chore/test-and-submodule-auto-updates
          delete-branch: true
